AarhusWebDevCoop/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AarhusWebDevCoop.ViewModels
{
    public class ContactForm
    {
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter your Email")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please write a subject")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "Please write a message")]
        public string Message { get; set; }
    }
}

AarhusWebDevCoop/Controllers/ContactFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using AarhusWebDevCoop.ViewModels;
using System.Net.Mail;

namespace AarhusWebDevCoop.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // GET: ContactFormSurface
        public ActionResult Index()
        {
            ContactForm model = new ContactForm();

            return PartialView("ContactForm", model);
        }
        // HELLO2

        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm model)
        {
            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            MailMessage message = new MailMessage();
            message.To.Add("slundmain@gmail.com");
            message.Subject = model.Subject;
            message.From = new MailAddress(model.Email, model.Name);
            message.Body = model.Message;

            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("supernemathuske@gmail.com", "Hejumbraco123");
                smtp.EnableSsl = true;
                // send mail
                smtp.Send(message);
            }

            IContent comment = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "message");

            comment.SetValue("messageName", model.Name);
            comment.SetValue("email", model.Email);
            comment.SetValue("subject", model.Subject);
            comment.SetValue("messageContent", model.Message);

            // Save
            Services.ContentService.Save(comment);


            TempData["success"] = true;
            return RedirectToCurrentUmbracoPage();
        }
    }
}

AarhusWebDevCoop/Views/AboutUs.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.AboutUs>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@CurrentPage.GetGridHtml("aboutGrid")

AarhusWebDevCoop/Views/ArticleItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticleItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<h2>@Umbraco.Field("articleTitle")</h2>
<p>@Umbraco.Field("articleContent")</p>

AarhusWebDevCoop/Views/ArticlesOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticlesOverview>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<h2>@Umbraco.Field("articlesTitle")</h2>
<p>@Umbraco.Field("articlesBodyText")</p>

<div class="col-md-8 col-md-offset-1">@Umbraco.RenderMacro("listChilds")</div>

AarhusWebDevCoop/Views/ContactUs.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ContactUs>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}

<div class="col-md-12">
    <h2>@CurrentPage.Name</h2>
    <hr />
</div>

<div class="col-sm-12">
    @Html.Action("Index", "ContactFormSurface")
</div>

AarhusWebDevCoop/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}
<div class="row">
    <div class="col-lg-12" style="padding-bottom:10px;">
        <h2>@Umbraco.Field("siteTitle")</h2>
    </div>
    <div class="col-md-6" style="max-width: 100%; height: auto;">
        <img src="@Umbraco.Media(@CurrentPage.logo.ToString()).Url" alt="" class="img-fluid" />
    </div>
    <div class="col-md-6">
        <p>
            @Umbraco.Field("mainContent")
        </p>
    </div>

    <div class="col-md-12">
        <br><hr />

        @Umbraco.RenderMacro("listNewestProjects", new { numOfProjects = "5" })
    </div>
</div>

<footer style="text-align:center">
    <div class="row">
        <div class="col-md-12">
            <hr />
            @Umbraco.Field("footer")
        </div>
    </div>
</footer>

AarhusWebDevCoop/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Login>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}


@Html.Partial("loginForm")

AarhusWebDevCoop/Views/MacroPartials/NavigationMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web


@*
    This snippet displays a list of links of the pages immediately under the top-most page in the content tree.
    This is the home page for a standard website.
    It also highlights the current active page/section in the navigation with the CSS class "current".
*@

@{ var root = Model.Content.Site(); }

@{ var selection =
                                  root
                                  .Children
                                  .Where(x => x.IsVisible())
                                  .ToArray(); }

@if (selection.Length > 0)
{
    foreach (var item in selection)
    {
        var isProtected = umbraco.library.IsProtected(item.Id, item.Path);
        var loginAccess = umbraco.library.IsProtected(item.Id, item.Path) && umbraco.library.HasAccess(item.Id, item.Path);

        if (!isProtected || loginAccess)
        {
            <li class="nav-item @(item.IsAncestorOrSelf(Model.Content) ? "active" : null)">
                <!-- // TODO: Smarter select of childs and project Items -->
                @if (item.Children().Where(x => x.IsVisible()).Count() > 0)
                {
                <li class="nav-item dropdown">
                    <a href="@item.Url" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" @*data-toggle="dropdown"*@ aria-haspopup="true" aria-expanded="false">
                        @item.Name
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        @foreach (var subMenuItem in item.Children().Where(x => x.IsVisible()))
                        {
                            var isSubProtected = umbraco.library.IsProtected(subMenuItem.Id, subMenuItem.Path);
                            var subLoginAccess = umbraco.library.IsProtected(subMenuItem.Id, subMenuItem.Path) && umbraco.library.HasAccess(subMenuItem.Id, subMenuItem.Path);


                            if (subMenuItem.DocumentTypeAlias == "projectItem")
                            {
                                if (umbraco.library.GetPreValueAsString(subMenuItem.GetPropertyValue<int>
                                    ("projectStatus")) == "Completed" && !isSubProtected || subLoginAccess)
                                {
                                    //Show project item
                                    <a class="dropdown-item" href="@subMenuItem.Url">@subMenuItem.Name</a>
                                }
                            }
                            else
                            {
                                // Show submenu
                                <a class="dropdown-item" href="@subMenuItem.Url">@subMenuItem.Name</a>
                            }
                        }
                    </div>
                </li>
            }
            else
            {
                <a class="nav-link" href="@item.Url">@item.Name</a>
            }
                </li>
        }
    }
}

AarhusWebDevCoop/Views/MacroPartials/contactForm.cshtml
@model AarhusWebDevCoop.ViewModels.ContactForm

@{
    Layout = null;
}

<form class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-6">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-6">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email address" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-6">
            @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-6">
            @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Your message" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
            <button id="contact-submit" type="submit" class="btn btn-primary input-medium pull- left">Send</button>
        </div>
    </div>
</form>

AarhusWebDevCoop/Views/MacroPartials/listActiveMembers.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web;
@using Newtonsoft.Json;
@using Umbraco.Web.Models;

@{ var memberService = ApplicationContext.Current.Services.MemberService;
    var members = memberService.GetMembersByGroup("Active");
}

<div class="row col-md-12">
    @foreach (var member in members)
    {
        String[] skills = member.GetValue("skills").ToString().Split(',');

        string skillString =
        string.Join(", ", from skill in skills
                          select umbraco.library.GetPreValueAsString(Convert.ToInt32(skill)));

        <div class="col-md-6">
            <p>
                @member.Name <br>
                @member.GetValue("address") <br>
                @member.GetValue("zip") @member.GetValue("city") <br />
                Email: @member.Email<br>
                Skills: @skillString
            </p>
        </div>


        @*if (member.GetValue("photo") != null)
        {
            string image = member.GetValue<string>("photo");
            if (image != null)
            {
                ImageCropDataSet imageCrop = JsonConvert.DeserializeObject<ImageCropDataSet>(image); string imagePath = imageCrop.Src.GetCropUrl(width: 150);
                <img src="@imagePath" />
            }
        }*@

        if (member.HasProperty("photo2") != null)
            {
            IPublishedContent mediaItem = Umbraco.TypedMedia(member.GetValue("photo2"));

            <div class="col-md-3 offset-md-3" style="max-width: 100%; height: auto;">
                <img src="@mediaItem.Url" alt="" class="img-fluid" />
            </div>
            }
    }
</div>

AarhusWebDevCoop/Views/MacroPartials/listChilds.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web


@*
    This snippet makes a list of links to the of children of the current page using an unordered HTML list.

    How it works:
    - It uses the Children method to get all child pages
    - It then uses the OrderBy() method, which takes the property to sort. In this case, the page's name.
    - It then generates links so the visitor can go to each page
*@

@{ var selection = Model.Content.Children.Where(x => x.IsVisible()).OrderBy(x => x.Name).ToArray(); }

@helper Truncate(string input, int length)
    {
        if (input.Length <= length)
        {
            @Html.Raw(input)
        }
        else
        {
            @Html.Raw(input.Substring(0, length))<text>...</text>
        }
}

@if (selection.Length > 0)
{
    foreach (var item in selection)
    {
        <h4>@item.Name</h4>
        var articleContent = item.GetPropertyValue("articleContent").ToString();
        <p>@Truncate(articleContent, 175) <a href="@item.Url"> Læs mere</a></p>

    }
}

AarhusWebDevCoop/Views/MacroPartials/listNewestProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web

@{ int numOfProjects = Convert.ToUInt16(Model.MacroParameters["numOfProjects"]); }

@{ var selection =
              Model.Content.Site()
              .Children
              .Where(x => x.DocumentTypeAlias == "projectsOverview")
              .First()
              .Children
              .Where(x => x.HasValue("projectStatus") && Umbraco.GetPreValueAsString(x.GetPropertyValue<int>("projectStatus")) == "Completed")
              .OrderBy(x => x.CreateDate)
              .Take(numOfProjects)
              .ToArray(); }

<h4>All completed projects:</h4>
@foreach (var item in selection)
{
    <ul>
        <li>
            <a href="@item.Url">@item.Name</a>
        </li>
    </ul>
}

AarhusWebDevCoop/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Master>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = null;
}

<html>
<head>

    <head>
        <meta charset="UTF-8">
        <meta name="description" content="@Umbraco.Field("metaDescription")">
        <meta name="keywords" content="@Umbraco.Field("metaKeywords")">
        <meta name="author" content="Søren Ravn Lund">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="~/Content/Styles/Custom.min.css" rel="stylesheet" />
    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-info">
            <div class="container">
                <a class="navbar-brand" href="/Homepage">DevsAarhus</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" @*aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"*@>
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                        @Umbraco.RenderMacro("NavigationMenu")
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/Umbraco">Admin</a>
                        </li>
                    </ul>
                </div>
            </div>

        </nav>

        <div class="container">
            <div class="row col-md-12">
                @RenderBody()
            </div>
        </div>

        <script src="~/Scripts/jquery-3.3.1.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>

        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    </body>

</html>

AarhusWebDevCoop/Views/Partials/ContactForm.cshtml
@model AarhusWebDevCoop.ViewModels.ContactForm

@{
    Layout = null;
}

@if (TempData["success"] == null)
{
    using (Html.BeginUmbracoForm("HandleFormSubmit", "ContactFormSurface", new object { },
            new { @class = "form-horizontal" }))
    {

        <div class="form-group row">
            @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email address" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
                @Html.ValidationMessageFor(m => m.Subject)
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Your message" })
                @Html.ValidationMessageFor(m => m.Message)
            </div>
        </div>
        <div class="form-group row">
            <div class="offset-sm-2 col-sm-6">
                <button id="contact-submit" type="submit" class="btn btn-primary input-medium pull-left">Send</button>
            </div>
        </div>
    }
}
else
{
    <p>Thank you for contacting us. We'll be in touch soon!</p>
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row);
                    }
                </div>
            }   
        }else { 
            <div class="row clearfix">
                @foreach (var s in Model.sections) {
                    <div class="grid-section">
                        <div class="col-md-@s.grid column">
                            @foreach (var row in s.rows) {
                                @renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@helper renderRow(dynamic row){
    <div @RenderElementAttributes(row)>
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

AarhusWebDevCoop/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))